[package]
name = "sonos-controller"
version = "0.1.0"
description = "Unofficial Sonos Controller for Linux"
authors = ["you"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "sonos_controller_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12" }
regex = "1"
roxmltree = "0.20"
log = "0.4"
url = "2"
open = "5"
urlencoding = "2"
